import dotenv from "dotenv";

dotenv.config();

export const env = {
  PORT: process.env.PORT || 3001,
  DATABASE_URL: process.env.DATABASE_URL!,
  FRONTEND_PUBLIC_BASE_URL: process.env.FRONTEND_PUBLIC_BASE_URL!,

  IMAGE_DEFAULT_USER: process.env.IMAGE_DEFAULT_USER!,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI!,

  JWT_TOKEN_EMAIL_VERIFICATION: process.env
    .JWT_TOKEN_EMAIL_VERIFICATION! as string,
  EMAIL_TOKEN_VERIFICATION_EXPIRES_IN:
    process.env.EMAIL_TOKEN_VERIFICATION_EXPIRES_IN!,
  EMAIL_HOST: process.env.EMAIL_HOST!,
  EMAIL_PORT: Number(process.env.EMAIL_PORT) || 587,
  EMAIL_SECURE: process.env.EMAIL_SECURE === "true",
  EMAIL_SERVICE: process.env.EMAIL_SERVICE!,
  EMAIL_USER: process.env.EMAIL_USER!,
  EMAIL_PASS: process.env.EMAIL_PASS!,

  JWT_ACCESS_TOKEN: process.env.JWT_ACCESS_TOKEN!,
  JWT_ACCESS_TOKEN_EXPIRES_IN: process.env.JWT_ACCESS_TOKEN_EXPIRES_IN!,
  JWT_REFRESH_TOKEN: process.env.JWT_REFRESH_TOKEN!,
  JWT_REFRESH_TOKEN_EXPIRES_IN: process.env.JWT_REFRESH_TOKEN_EXPIRES_IN!,

  UPLOADTHING_TOKEN: process.env.UPLOADTHING_TOKEN!,
};
