export enum Role {
  ADMIN = "admin",
  SUPERADMIN = "super_admin",
  CUSTOMER = "customer",
}

export enum Permission {
  CREATE_CATEGORY = "CREATE_CATEGORY",
  UPDATE_CATEGORY = "UPDATE_CATEGORY",
  DELETE_CATEGORY = "DELETE_CATEGORY",
  VIEW_CATEGORY = "VIEW_CATEGORY",

  CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY",
  UPDATE_SUB_CATEGORY = "UPDATE_SUB_CATEGORY",
  DELETE_SUB_CATEGORY = "DELETE_SUB_CATEGORY",
  VIEW_SUB_CATEGORY = "VIEW_SUB_CATEGORY",
}
